apiVersion: v1
kind: Service
metadata:
  name: koa-example
  labels:
    app: koa-example
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    app: koa-example
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: koa-example
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: koa-example
    spec:
      containers:
      - name: koa-example
        image: stevenacoffman/koa_kubernetes_example:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8888
        # resources:
        #   limits:
        #     cpu: 0.2
        #     memory: "10Mi"
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8888
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   periodSeconds: 15
        #   timeoutSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /readiness
        #     port: 8888
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 1
